# Generated by Django 5.1.6 on 2025-03-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authsystem", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userimage",
            unique_together={("user", "image_hash")},
        ),
    ]
